swagger: '2.0'
info:
  version: '1.0.0'
  title: Sections API
components:
  schemas:
    section:
      type: object
      required:
        - name             
      properties:
        name:
          type: string
          description: section name
        additionalconsiderations:
          type: string
          description: section additionalconsiderations
        awe:
          type: string
          description: section awe
        conditionalassessment:
          type: string
          description: section conditionalassessment
        createdby:
          type: string
          description: section createdby
        eee:
          type: string
          description: section eee
        exteriorelements:
          type: array
          items:
            type: string
          description: section exteriorelements     
        furtherinvasivereviewrequired:
          type: string
          description: section furtherinvasivereviewrequired
        lbc:
          type: string
          description: section lbc
        parentid:
          type: string
          description: section parentid
        parenttype:
          type: string
          description: section parenttype
        visualreview:
          type: string
          description: section visualreview
        visualsignsofleak:
          type: boolean
          description: section visualsignsofleak
        waterproofingelements:
          type: array
          items:
            type: string
          description: section waterproofingelements
        images:
          type: array
          items:
            type: string
          description: subproject images          
    uploadOtions:
      type: object

paths:
  /api/section/add:
    
    post:
      tags:
        [Section]
      summary: add Section
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/section'
      responses:
        201:
          description: section uploaded successfully 
        400:
          description: Invalid input, inputs are missing
        500:
          description: Internal server error


  /api/section/{id}:
    
    put:
      tags:
        [Section]
      summary: edit Section
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Section.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/section'
      responses:
        201:
          description: section uploaded successfully 
        400:
          description: Invalid input, inputs are missing
        500:
          description: Internal server error

  /api/section/getSectionById:
    post:
      tags:
        - Section
      summary: Get section by Id
      description: Get section by id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sectionid:
                  type: string
                  description: The ID of the section.
                username:
                  type: string
                  description: The username of the user sending the request.
      responses:
        '201':
          description: Section retrieved.
        '401':
          description: No projects found.
        '500':
          description: Internal server error.
    
/api/section/{id}:
  delete:
      tags:
        [Section]
      summary: delete section by id
      parameters:
        - name: id
          in: path
          required: true
          description: The section Id.
          schema:
            type: string
      responses:
        201:
          description: section deleted successfully.        
        401:
          description: No section founds.
        500:
          description: Internal server error.