swagger: '2.0'
info:
  version: '1.0.0'
  title: subproject API
components:
  schemas:
    subproject:
      type: object
      required:
        - name             
      properties:
        name:
          type: string
          description: subproject name
        description:
          type: string
          description: subproject description
        parentid:
          type: string
          description: subproject parentProjectId
        parenttype:
          type: string
          description: subproject parentProjectType
        isInvasive:
          type: boolean
          description: subproject isInvasive
        createdBy:
          type: string
          description: subproject created by
        url:
          type: string
          description: local full filepath.
        assignedTo:
          type: array
          items:
            type: string
          description: subproject assigned to          
    uploadOtions:
      type: object

paths:
  /api/subproject/add:
    
    post:
      tags:
        [SubProject]
      summary: add subproject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subproject'
      responses:
        201:
          description: subproject uploaded successfully 
        400:
          description: Invalid input, inputs are missing
        500:
          description: Internal server error


  /api/subproject/{id}:
    
    put:
      tags:
        [SubProject]
      summary: Edit subproject
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the subProject.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subproject'
      responses:
        201:
          description: subproject uploaded successfully 
        400:
          description: Invalid input, inputs are missing
        500:
          description: Internal server error

  /api/subproject/getSubprojectsDataByProjectId:
    post:
      tags:
        - SubProject
      summary: Get subproject by project Id
      description: Get subproject by project Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectid:
                  type: string
                  description: The ID of the projectid.
                username:
                  type: string
                  description: The username of the user sending the request.
      responses:
        '201':
          description: subproject retrieved.
        '401':
          description: No subproject found.
        '500':
          description: Internal server error.
  
  /api/subproject/getSubProjectById:
     post:
      tags:
        - SubProject
      summary: Get SubProject by Id
      description: Get SubProject by Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subprojectid:
                  type: string
                  description: The ID of the subProject.
                username:
                  type: string
                  description: The username of the user sending the request.
      responses:
        '201':
          description: Location retrieved.
        '401':
          description: No Location found.
        '500':
          description: Internal server error.

/api/subproject/{id}:
  delete:
      tags:
        [SubProject]
      summary: delete subproject by id
      parameters:
        - name: id
          in: path
          required: true
          description: The subproject Id.
          schema:
            type: string
      responses:
        201:
          description: subproject deleted successfully.        
        401:
          description: No subproject founds.
        500:
          description: Internal server error.